#!/usr/bin/env bash

# Generate grpc files from here to add the package path to the import statements.
python -m grpc_tools.protoc -I. --python_out=. --pyi_out=. --grpc_python_out=. chargepal_local_server/communication.proto
